services:
  backend:
    build:
      context: ./
      target: backend-dev
    ports:
      - 5173:5173
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017/
      PORT: 5173
    depends_on:
      - mongodb
    restart: always

  client:
    build:
      context: ./
      target: client-dev
    ports:
      - 3000:3000

  mongodb:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongodb-log:/var/log/mongodb/

volumes:
  mongo-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log
